using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;



public sealed class BearerSecuritySchemeTransformer(IConfiguration configuration) : IOpenApiDocumentTransformer
{
    public Task TransformAsync(OpenApiDocument document, OpenApiDocumentTransformerContext context, CancellationToken cancellationToken)
    {
        var jwtToken = configuration["Authentication:JwtToken"] ?? "JWT_KEY_NOT_FOUND";

        var bearerScheme = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "JWT",
            //Description = "Enter your JWT token generated by 'dotnet user-jwts'."
            Description = $"Enter your JWT token. (Secret Configuration Key: {jwtToken})",
        };

        document.Components ??= new OpenApiComponents();

        document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
        document.Components.SecuritySchemes["BearerAuth"] = bearerScheme;

        return Task.CompletedTask;
    }
}
